# Generated by Django 5.1.6 on 2025-02-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fast_food', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
