# Generated by Django 5.1.6 on 2025-02-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fast_food", "0005_remove_cartitem_cart_remove_cartitem_total_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="cart_items",
        ),
        migrations.AddField(
            model_name="orders",
            name="address",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
