# Generated by Django 5.1.6 on 2025-02-14 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fast_food", "0006_remove_orders_cart_items_orders_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_items",
                to="fast_food.product",
            ),
        ),
    ]
